import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';

type Template = { id: string; name: string; body: string };

// ===== embedded template bodies (ported verbatim from WinForge GitignoreService) =====

const NodeBody = `node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
.pnpm-store/
.npm
.yarn/
dist/
build/
coverage/
.env
.env.local
.env.*.local
.cache/
.next/
.nuxt/
.parcel-cache/
*.tsbuildinfo`;

const PythonBody = `__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
dist/
*.egg-info/
.eggs/
.installed.cfg
*.egg
.pytest_cache/
.mypy_cache/
.ruff_cache/
.coverage
htmlcov/
.tox/
.venv/
venv/
env/
ENV/
*.log`;

const VisualStudioBody = `bin/
obj/
.vs/
*.user
*.suo
*.userosscache
*.sln.docstates
*.userprefs
[Dd]ebug/
[Rr]elease/
x64/
x86/
[Bb]in/
[Oo]bj/
*.pdb
*.cache
packages/
*.nupkg
TestResults/
.vsconfig`;

const VsCodeBody = `.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets
.history/
*.vsix`;

const JetBrainsBody = `.idea/
*.iml
*.ipr
*.iws
out/
.idea_modules/
atlassian-ide-plugin.xml
cmake-build-*/
*.iws`;

const RustBody = `/target/
**/*.rs.bk
Cargo.lock
*.pdb`;

const JavaBody = `target/
*.class
*.jar
*.war
*.ear
*.nar
hs_err_pid*
replay_pid*
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar
build/
.gradle/`;

const GoBody = `*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
go.work
go.work.sum
vendor/
bin/`;

const CppBody = `*.o
*.obj
*.a
*.lib
*.so
*.dylib
*.dll
*.exe
*.out
*.app
*.gch
*.pch
build/
cmake-build-*/
CMakeFiles/
CMakeCache.txt`;

const MacOsBody = `.DS_Store
.AppleDouble
.LSOverride
Icon
._*
.Spotlight-V100
.Trashes
.fseventsd
.DocumentRevisions-V100
.TemporaryItems
.apdisk`;

const WindowsBody = `Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db
Desktop.ini
$RECYCLE.BIN/
*.stackdump
*.cab
*.msi
*.msix
*.lnk`;

const LinuxBody = `*~
.fuse_hidden*
.directory
.Trash-*
.nfs*
.cache/`;

// All built-in templates, in display order (matches WinForge GitignoreService.Templates).
const TEMPLATES: Template[] = [
  { id: 'node', name: 'Node', body: NodeBody },
  { id: 'python', name: 'Python', body: PythonBody },
  { id: 'visualstudio', name: 'Visual Studio', body: VisualStudioBody },
  { id: 'vscode', name: 'VS Code', body: VsCodeBody },
  { id: 'jetbrains', name: 'JetBrains', body: JetBrainsBody },
  { id: 'rust', name: 'Rust', body: RustBody },
  { id: 'java', name: 'Java / Maven', body: JavaBody },
  { id: 'go', name: 'Go', body: GoBody },
  { id: 'cpp', name: 'C / C++', body: CppBody },
  { id: 'macos', name: 'macOS', body: MacOsBody },
  { id: 'windows', name: 'Windows', body: WindowsBody },
  { id: 'linux', name: 'Linux', body: LinuxBody },
];

// Concatenate the chosen templates into a single .gitignore. Each template goes
// under a "### <name> ###" header; identical non-blank, non-comment lines that
// already appeared earlier are dropped so the result has no duplicate rules.
// Ported from GitignoreService.Combine. Never throws — returns "" on trouble.
function combine(chosen: Template[]): string {
  try {
    if (chosen.length === 0) return '';

    const seen = new Set<string>();
    const parts: string[] = [];
    parts.push('# Generated by WinForge · WinForge 產生\n');
    parts.push('# https://github.com — combine common .gitignore templates\n\n');

    for (const t of chosen) {
      parts.push('### ' + t.name + ' ###\n');
      const body = t.body ?? '';
      for (const raw of body.replace(/\r\n/g, '\n').split('\n')) {
        const line = raw.replace(/\s+$/, '');
        const trimmed = line.trim();
        // Always keep blank lines and comments for readability; de-dup real rules only.
        if (trimmed.length === 0 || trimmed.startsWith('#')) {
          parts.push(line + '\n');
          continue;
        }
        if (!seen.has(trimmed)) {
          seen.add(trimmed);
          parts.push(line + '\n');
        }
      }
      parts.push('\n');
    }

    return parts.join('').replace(/\n+$/, '') + '\n';
  } catch {
    return '';
  }
}

function countLines(text: string): number {
  if (!text) return 0;
  return text.replace(/\r\n/g, '\n').replace(/\n+$/, '').split('\n').length;
}

export function GitignoreModule() {
  const { t } = useTranslation();
  const [selected, setSelected] = useState<Record<string, boolean>>({});
  const [status, setStatus] = useState('');

  const chosen = useMemo(() => TEMPLATES.filter((tpl) => selected[tpl.id]), [selected]);
  const output = useMemo(() => combine(chosen), [chosen]);

  const toggle = (id: string) => setSelected((prev) => ({ ...prev, [id]: !prev[id] }));

  const copy = () => {
    if (output.length === 0) {
      setStatus(t('gitignore.nothingToCopy'));
      return;
    }
    void navigator.clipboard?.writeText(output);
    setStatus(t('gitignore.copied'));
  };

  const save = () => {
    if (output.length === 0) {
      setStatus(t('gitignore.nothingToSave'));
      return;
    }
    try {
      const blob = new Blob([output], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = '.gitignore';
      a.click();
      URL.revokeObjectURL(url);
      setStatus(t('gitignore.saved'));
    } catch (e) {
      setStatus(t('gitignore.saveFailed') + String(e instanceof Error ? e.message : e));
    }
  };

  const statusText =
    status ||
    (chosen.length === 0
      ? t('gitignore.pickToStart')
      : t('gitignore.combined', { n: chosen.length, lines: countLines(output) }));

  return (
    <div className="mod">
      <p className="count-note" style={{ marginTop: 0 }}>
        {t('gitignore.blurb')}
      </p>
      <div className="io-grid" style={{ gridTemplateColumns: 'minmax(200px, 260px) 1fr' }}>
        <div>
          <h3 className="group-title" style={{ fontSize: 15, margin: '0 0 8px' }}>
            {t('gitignore.templates')}
          </h3>
          <div className="kv-list" style={{ maxHeight: 420, overflow: 'auto' }}>
            {TEMPLATES.map((tpl) => (
              <label key={tpl.id} className="chk" style={{ display: 'flex', gap: 8, padding: '4px 2px' }}>
                <input
                  type="checkbox"
                  checked={!!selected[tpl.id]}
                  onChange={() => {
                    setStatus('');
                    toggle(tpl.id);
                  }}
                />
                {tpl.name}
              </label>
            ))}
          </div>
        </div>
        <div>
          <div className="mod-toolbar" style={{ marginTop: 0 }}>
            <h3 className="group-title" style={{ fontSize: 15, margin: 0, flex: 1 }}>
              {t('gitignore.output')}
            </h3>
            <button className="mini" onClick={copy} disabled={output.length === 0}>
              {t('gitignore.copy')}
            </button>
            <button className="mini primary" onClick={save} disabled={output.length === 0}>
              {t('gitignore.save')}
            </button>
          </div>
          <textarea
            className="hosts-edit"
            spellCheck={false}
            readOnly
            value={output}
            style={{ minHeight: 360, fontFamily: 'Consolas, ui-monospace, monospace', whiteSpace: 'pre' }}
            placeholder={t('gitignore.pickToStart')}
          />
          <p className="count-note" style={{ marginTop: 8 }}>
            {statusText}
          </p>
        </div>
      </div>
    </div>
  );
}
