import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { pick } from '../i18n';

// Port of WinForge HostsEditService — a safe, client-side hosts-file editor.
// Parse pasted hosts text into entries, toggle enable/disable, add or block
// domains via curated presets, then rebuild canonical hosts text. The desktop
// app's "load system file" / "write back" (which need OS access + admin) are
// replaced with paste-in and copy / download, which work fully offline.

interface HostEntry {
  enabled: boolean;
  ip: string;
  hosts: string;
  comment: string;
}

interface Preset {
  en: string;
  zh: string;
  domains: string[];
}

// Curated block-list presets — copied verbatim from HostsEditService.Presets.
const PRESETS: Preset[] = [
  {
    en: 'Common ad servers',
    zh: '常見廣告伺服器',
    domains: [
      'doubleclick.net', 'ad.doubleclick.net', 'pagead2.googlesyndication.com',
      'googleads.g.doubleclick.net', 'adservice.google.com', 'ads.yahoo.com',
    ],
  },
  {
    en: 'Trackers & analytics',
    zh: '追蹤器同分析',
    domains: [
      'google-analytics.com', 'www.google-analytics.com', 'ssl.google-analytics.com',
      'connect.facebook.net', 'graph.facebook.com', 'analytics.tiktok.com',
    ],
  },
  {
    en: 'Telemetry (misc)',
    zh: '遙測（雜項）',
    domains: [
      'app-measurement.com', 'in.appcenter.ms', 'data.flurry.com',
      'settings-win.data.microsoft.com', 'vortex.data.microsoft.com',
    ],
  },
];

// ===== IP validation (IPv4 + IPv6) — mirrors .NET IPAddress.TryParse intent. =====

function isIPv4(s: string): boolean {
  const parts = s.split('.');
  if (parts.length !== 4) return false;
  for (const p of parts) {
    if (p.length === 0 || p.length > 3) return false;
    if (!/^[0-9]+$/.test(p)) return false;
    const n = Number(p);
    if (n < 0 || n > 255) return false;
    // reject leading zeros like "01" except the single "0"
    if (p.length > 1 && p.charAt(0) === '0') return false;
  }
  return true;
}

function isIPv6(s: string): boolean {
  // Reject obvious non-candidates fast.
  if (s.indexOf(':') < 0) return false;
  // At most one "::" (zero-run compression).
  const dc = s.split('::').length - 1;
  if (dc > 1) return false;

  let head = s;
  let tailV4 = '';
  // Optional embedded IPv4 in the last group.
  const lastColon = s.lastIndexOf(':');
  const afterLastColon = s.slice(lastColon + 1);
  if (afterLastColon.indexOf('.') >= 0) {
    if (!isIPv4(afterLastColon)) return false;
    head = s.slice(0, lastColon + 1);
    tailV4 = 'ffff'; // stands in for the two 16-bit groups the IPv4 covers
  }

  const hextets = (head + tailV4).split(':');
  let empties = 0;
  let real = 0;
  for (const h of hextets) {
    if (h.length === 0) { empties++; continue; }
    if (h.length > 4 || !/^[0-9a-fA-F]+$/.test(h)) return false;
    real++;
  }
  if (dc === 1) return real <= 7; // "::" fills the rest
  // No compression: must be exactly 8 groups, no stray empties (except we
  // consumed the v4 tail into one placeholder group).
  const target = tailV4 ? 7 : 8;
  return empties === 0 && real === target;
}

function isValidIp(s: string): boolean {
  const v = s.trim();
  if (v.length === 0) return false;
  return isIPv4(v) || isIPv6(v);
}

// ===== parsing =====

function looksLikeEntry(s: string): boolean {
  const parts = s.split(/[ \t]+/).filter((p) => p.length > 0);
  return parts.length >= 2 && isValidIp(parts[0]!);
}

function parseHosts(text: string): HostEntry[] {
  const out: HostEntry[] = [];
  if (!text) return out;
  const lines = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');
  for (const raw of lines) {
    const line = raw.replace(/[ \t]+$/, '');
    const trimmed = line.replace(/^[ \t]+/, '');
    if (trimmed.length === 0) continue;

    let enabled = true;
    let body = trimmed;
    if (trimmed.startsWith('#')) {
      // A commented line MAY be a disabled entry ("# 0.0.0.0 host") or a pure comment.
      const afterHash = trimmed.replace(/^#+/, '').replace(/^[ \t]+/, '');
      if (looksLikeEntry(afterHash)) {
        enabled = false;
        body = afterHash;
      } else {
        continue; // pure comment — dropped
      }
    }

    // split inline trailing comment
    let comment = '';
    const hashIdx = body.indexOf('#');
    if (hashIdx >= 0) {
      comment = body.slice(hashIdx + 1).trim();
      body = body.slice(0, hashIdx).trim();
    }
    const parts = body.split(/[ \t]+/).filter((p) => p.length > 0);
    if (parts.length < 2) continue;

    const ip = parts[0]!;
    const hosts = parts.slice(1).join(' ');
    out.push({ enabled, ip, hosts, comment });
  }
  return out;
}

// ===== rebuild =====

function buildText(entries: HostEntry[]): string {
  let out = '';
  out += '# Hosts file — generated by WinForge · 由 WinForge 產生\n';
  out += '# 127.0.0.1  localhost\n';
  out += '\n';
  for (const e of entries) {
    if (e.ip.trim().length === 0 || e.hosts.trim().length === 0) continue;
    let line = `${e.ip}\t${e.hosts}`;
    if (e.comment.trim().length > 0) line += `    # ${e.comment}`;
    if (!e.enabled) line = '# ' + line;
    out += line + '\n';
  }
  return out;
}

function displayOf(e: HostEntry): string {
  return e.comment.trim().length === 0
    ? `${e.ip}  →  ${e.hosts}`
    : `${e.ip}  →  ${e.hosts}   # ${e.comment}`;
}

const SAMPLE = `# Sample hosts file — paste your own or edit below
127.0.0.1\tlocalhost
::1\tlocalhost
0.0.0.0\tads.example.com    # blocked
# 192.168.1.50\tnas.local    # disabled entry
`;

export function HostsEditModule() {
  const { t, i18n } = useTranslation();
  const lang = i18n.language;

  const [entries, setEntries] = useState<HostEntry[]>(() => parseHosts(SAMPLE));
  const [selected, setSelected] = useState<number>(-1);
  const [presetIdx, setPresetIdx] = useState<number>(0);

  const [pasteText, setPasteText] = useState<string>(SAMPLE);

  const [ip, setIp] = useState<string>('');
  const [host, setHost] = useState<string>('');
  const [comment, setComment] = useState<string>('');

  const [status, setStatus] = useState<{ ok: boolean; msg: string } | null>(null);

  const output = useMemo(() => buildText(entries), [entries]);

  const say = (ok: boolean, msg: string) => setStatus({ ok, msg });

  const doParse = () => {
    const parsed = parseHosts(pasteText);
    setEntries(parsed);
    setSelected(-1);
    say(true, t('hostsedit.parsed', { count: parsed.length }));
  };

  const doClear = () => {
    setEntries([]);
    setSelected(-1);
    say(true, t('hostsedit.cleared'));
  };

  const doAdd = () => {
    const ipT = ip.trim();
    const hostT = host.trim();
    if (!isValidIp(ipT)) {
      say(false, t('hostsedit.badIp', { ip: ipT }));
      return;
    }
    if (hostT.length === 0) {
      say(false, t('hostsedit.needHost'));
      return;
    }
    setEntries((prev) => [...prev, { enabled: true, ip: ipT, hosts: hostT, comment: comment.trim() }]);
    setIp('');
    setHost('');
    setComment('');
    say(true, t('hostsedit.added', { ip: ipT, hosts: hostT }));
  };

  const doApplyPreset = () => {
    const preset = PRESETS[presetIdx];
    if (!preset) {
      say(false, t('hostsedit.pickPreset'));
      return;
    }
    setEntries((prev) => {
      const existing = new Set<string>();
      for (const e of prev) {
        for (const h of e.hosts.split(/[ \t]+/).filter((x) => x.length > 0)) {
          existing.add(h.toLowerCase());
        }
      }
      const additions: HostEntry[] = [];
      for (const d of preset.domains) {
        if (existing.has(d.toLowerCase())) continue;
        additions.push({ enabled: true, ip: '0.0.0.0', hosts: d, comment: pick('blocked', '已封鎖', lang) });
        existing.add(d.toLowerCase());
      }
      say(true, t('hostsedit.presetAdded', { count: additions.length, name: pick(preset.en, preset.zh, lang) }));
      return [...prev, ...additions];
    });
  };

  const doRemove = () => {
    if (selected < 0 || selected >= entries.length) {
      say(false, t('hostsedit.selectToRemove'));
      return;
    }
    setEntries((prev) => prev.filter((_, i) => i !== selected));
    setSelected(-1);
    say(true, t('hostsedit.removed'));
  };

  const toggle = (idx: number) => {
    setEntries((prev) => prev.map((e, i) => (i === idx ? { ...e, enabled: !e.enabled } : e)));
  };

  const doCopy = () => {
    void navigator.clipboard?.writeText(output);
    say(true, t('hostsedit.copied'));
  };

  const doDownload = () => {
    const blob = new Blob([output], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'hosts.txt';
    a.click();
    URL.revokeObjectURL(url);
    say(true, t('hostsedit.downloaded'));
  };

  const cardStyle = { marginTop: 14 } as const;
  const h3Style = { fontSize: 15, margin: 0, fontWeight: 600 } as const;

  return (
    <div className="mod">
      <p className="count-note" style={{ marginTop: 0 }}>
        {t('hostsedit.blurb')}
      </p>

      {/* Paste + presets */}
      <div className="kv-list" style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        <h3 style={h3Style}>{t('hostsedit.loadTitle')}</h3>
        <textarea
          className="hosts-edit"
          spellCheck={false}
          value={pasteText}
          onChange={(e) => setPasteText(e.target.value)}
          placeholder={t('hostsedit.pastePlaceholder')}
          style={{ minHeight: 120, fontFamily: 'Consolas, monospace' }}
        />
        <div className="mod-toolbar">
          <button className="mini primary" onClick={doParse}>{t('hostsedit.parseBtn')}</button>
          <button className="mini" onClick={doClear}>{t('hostsedit.clearAll')}</button>
        </div>
        <div className="mod-toolbar" style={{ alignItems: 'center' }}>
          <span className="count-note">{t('hostsedit.presetLabel')}</span>
          <select
            className="mod-select"
            value={presetIdx}
            onChange={(e) => setPresetIdx(Number(e.target.value))}
          >
            {PRESETS.map((p, i) => (
              <option key={i} value={i}>{pick(p.en, p.zh, lang)}</option>
            ))}
          </select>
          <button className="mini" onClick={doApplyPreset}>{t('hostsedit.addPreset')}</button>
        </div>
      </div>

      {/* Add entry */}
      <div className="kv-list" style={{ ...cardStyle, display: 'flex', flexDirection: 'column', gap: 10 }}>
        <h3 style={h3Style}>{t('hostsedit.addTitle')}</h3>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
          <span className="count-note" style={{ margin: 0, minWidth: 92 }}>{t('hostsedit.ipLabel')}</span>
          <input className="mod-search" style={{ flex: 1, minWidth: 160, fontFamily: 'Consolas, monospace' }} value={ip} onChange={(e) => setIp(e.target.value)} placeholder="0.0.0.0" />
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
          <span className="count-note" style={{ margin: 0, minWidth: 92 }}>{t('hostsedit.hostLabel')}</span>
          <input className="mod-search" style={{ flex: 1, minWidth: 160, fontFamily: 'Consolas, monospace' }} value={host} onChange={(e) => setHost(e.target.value)} placeholder="example.com" />
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
          <span className="count-note" style={{ margin: 0, minWidth: 92 }}>{t('hostsedit.commentLabel')}</span>
          <input className="mod-search" style={{ flex: 1, minWidth: 160 }} value={comment} onChange={(e) => setComment(e.target.value)} />
        </div>
        <button className="mini primary" style={{ alignSelf: 'flex-start' }} onClick={doAdd}>{t('hostsedit.addBtn')}</button>
      </div>

      {/* Entries */}
      <div className="kv-list" style={{ ...cardStyle, display: 'flex', flexDirection: 'column', gap: 10 }}>
        <h3 style={h3Style}>{t('hostsedit.listTitle')}</h3>
        {entries.length === 0 ? (
          <p className="count-note" style={{ margin: 0 }}>{t('hostsedit.noEntries')}</p>
        ) : (
          <div className="dt-wrap" style={{ maxHeight: 340 }}>
            {entries.map((e, i) => (
              <div
                key={i}
                onClick={() => setSelected(i)}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 10,
                  padding: '6px 8px',
                  cursor: 'pointer',
                  borderRadius: 6,
                  background: i === selected ? 'var(--accent-soft, rgba(120,120,255,0.15))' : 'transparent',
                  opacity: e.enabled ? 1 : 0.5,
                }}
              >
                <label className="chk" style={{ margin: 0 }} onClick={(ev) => ev.stopPropagation()}>
                  <input type="checkbox" checked={e.enabled} onChange={() => toggle(i)} />
                </label>
                <span style={{ fontFamily: 'Consolas, monospace', fontSize: 13, wordBreak: 'break-all' }}>
                  {displayOf(e)}
                </span>
              </div>
            ))}
          </div>
        )}
        <div className="mod-toolbar">
          <button className="mini" onClick={doRemove}>{t('hostsedit.removeSelected')}</button>
          <span className="count-note">{t('hostsedit.entryCount', { count: entries.length })}</span>
        </div>
      </div>

      {/* Output */}
      <div className="kv-list" style={{ ...cardStyle, display: 'flex', flexDirection: 'column', gap: 10 }}>
        <h3 style={h3Style}>{t('hostsedit.outputTitle')}</h3>
        <textarea
          className="hosts-edit"
          spellCheck={false}
          readOnly
          value={output}
          style={{ minHeight: 160, fontFamily: 'Consolas, monospace', whiteSpace: 'pre' }}
        />
        <div className="mod-toolbar">
          <button className="mini" onClick={doCopy}>{t('hostsedit.copyOutput')}</button>
          <button className="mini" onClick={doDownload}>{t('hostsedit.download')}</button>
        </div>
        <p className="count-note" style={{ margin: 0 }}>{t('hostsedit.writeBackNote')}</p>
      </div>

      {status && (
        <p
          className={status.ok ? 'count-note' : ''}
          style={status.ok ? { marginTop: 12 } : { marginTop: 12, color: 'var(--danger)', fontSize: 12.5 }}
        >
          {status.msg}
        </p>
      )}
    </div>
  );
}
