// Generate docs/PARITY.md — the WinForge-parity worklist that drives the Ralph loop.
// Status per module: working (real component) | partial (live probe) | stub (card only).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

const catalogTs = fs.readFileSync(path.join(root, 'src/data/catalog.ts'), 'utf8');
const m = catalogTs.match(/export const allModules: CatalogModule\[\] = (\[[\s\S]*?\]);\s*\nexport const moduleCount/);
if (!m) throw new Error('could not extract allModules');
const allModules = JSON.parse(m[1]);

const registry = fs.readFileSync(path.join(root, 'src/modules/registry.tsx'), 'utf8');
const working = new Set([...registry.matchAll(/'(module\.[a-z0-9]+)':/g)].map((x) => x[1]));

const native = fs.readFileSync(path.join(root, 'src/tauri/nativeActions.ts'), 'utf8');
const partial = new Set([...native.matchAll(/'(module\.[a-z0-9]+)':/g)].map((x) => x[1]));

const status = (tag) => (working.has(tag) ? 'working' : partial.has(tag) ? 'partial' : 'stub');

const counts = { working: 0, partial: 0, stub: 0 };
for (const mod of allModules) counts[status(mod.tag)]++;
const total = allModules.length;
const pct = (n) => ((n / total) * 100).toFixed(1);

let out = `# WinForge parity worklist

Auto-generated by \`node tools/gen-parity.mjs\`. Drives the Ralph loop: each iteration,
take the next **stub** (or upgrade a **partial**), read the matching WinForge page under
\`WinForge/Pages/<Name>Module.xaml{,.cs}\`, implement the real UI + backend, verify, commit.

**Progress: ${counts.working} working · ${counts.partial} partial · ${counts.stub} stub — of ${total} modules**
(${pct(counts.working)}% working, ${pct(counts.working + counts.partial)}% at least partial)

Legend: ✅ working · 🟡 partial (live probe only) · ⬜ stub (not yet ported)

`;

const icon = { working: '✅', partial: '🟡', stub: '⬜' };
// Emit worklist: partial first (quick wins to upgrade), then stubs, then working.
for (const bucket of ['partial', 'stub', 'working']) {
  const rows = allModules.filter((mod) => status(mod.tag) === bucket);
  out += `\n## ${icon[bucket]} ${bucket} (${rows.length})\n\n`;
  for (const mod of rows) {
    out += `- ${icon[bucket]} \`${mod.tag}\` — ${mod.en} · ${mod.zh}\n`;
  }
}

fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
fs.writeFileSync(path.join(root, 'docs/PARITY.md'), out);
console.log(`PARITY.md: ${counts.working} working, ${counts.partial} partial, ${counts.stub} stub (of ${total})`);
