// AUTO-GENERATED by tools/gen-tweak-ops.mjs from WinForge Catalog/*.cs (Tweak.RegToggle / RegRadio)
// plus a small set of hand-verified bespoke-helper ops (see MANUAL_OPS in the generator).
// Do not hand-edit. The concrete registry operation behind each tweak, so the desktop (Tauri)
// app can APPLY the tweak for real via the backend — mirroring RegistryHelper exactly.
// 154 toggles + 12 radios = 166 tweaks with a real op.
/* eslint-disable */

export type RegRoot = 'HKCU' | 'HKLM' | 'HKCR' | 'HKU';
export type RegKind = 'DWord' | 'QWord' | 'String' | 'ExpandString' | 'MultiString' | 'Binary';

export interface RegToggleOp {
  id: string;
  op: 'toggle';
  root: RegRoot;
  path: string;
  name: string;
  /** Value written / compared for the ON state. */
  on: number | string;
  /** Value for OFF; null ⇒ the value is deleted when turned off. */
  off: number | string | null;
  kind: RegKind;
  /** Needs elevation (HKLM or explicitly flagged). */
  admin: boolean;
}
export interface RegRadioOp {
  id: string;
  op: 'radio';
  root: RegRoot;
  path: string;
  name: string;
  kind: RegKind;
  options: { en: string; zh: string; value: number | string }[];
  admin: boolean;
}
export type TweakOp = RegToggleOp | RegRadioOp;

export const tweakOps: Record<string, TweakOp> = {
  "appearance.accent-start-taskbar": {
    "id": "appearance.accent-start-taskbar",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",
    "name": "ColorPrevalence",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "appearance.accent-titlebars": {
    "id": "appearance.accent-titlebars",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\DWM",
    "name": "ColorPrevalence",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "appearance.alpha-select": {
    "id": "appearance.alpha-select",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ListviewAlphaSelect",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "appearance.clock-seconds": {
    "id": "appearance.clock-seconds",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ShowSecondsInSystemClock",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "appearance.drag-full-windows": {
    "id": "appearance.drag-full-windows",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Desktop",
    "name": "DragFullWindows",
    "on": "1",
    "off": "0",
    "kind": "String",
    "admin": false
  },
  "appearance.icon-shadow": {
    "id": "appearance.icon-shadow",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ListviewShadow",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "appearance.snap-flyout": {
    "id": "appearance.snap-flyout",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "EnableSnapAssistFlyout",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "appearance.start-layout": {
    "id": "appearance.start-layout",
    "op": "radio",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "Start_Layout",
    "kind": "DWord",
    "options": [
      {
        "en": "Default",
        "zh": "預設",
        "value": 0
      },
      {
        "en": "More pins",
        "zh": "更多釘選",
        "value": 1
      },
      {
        "en": "More recommendations",
        "zh": "更多建議",
        "value": 2
      }
    ],
    "admin": false
  },
  "appearance.taskbar-animations": {
    "id": "appearance.taskbar-animations",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "TaskbarAnimations",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "appearance.taskbar-glom": {
    "id": "appearance.taskbar-glom",
    "op": "radio",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "TaskbarGlomLevel",
    "kind": "DWord",
    "options": [
      {
        "en": "Always combine, hide labels",
        "zh": "永遠合併、收埋標籤",
        "value": 0
      },
      {
        "en": "Combine when taskbar is full",
        "zh": "工作列滿先合併",
        "value": 1
      },
      {
        "en": "Never combine",
        "zh": "永遠唔合併",
        "value": 2
      }
    ],
    "admin": false
  },
  "appearance.transparency": {
    "id": "appearance.transparency",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",
    "name": "EnableTransparency",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "appearance.window-animations": {
    "id": "appearance.window-animations",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Desktop\\WindowMetrics",
    "name": "MinAnimate",
    "on": "1",
    "off": "0",
    "kind": "String",
    "admin": false
  },
  "br.policies.chrome-autofill-addresses": {
    "id": "br.policies.chrome-autofill-addresses",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Google\\Chrome",
    "name": "AutofillAddressEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.chrome-background-mode": {
    "id": "br.policies.chrome-background-mode",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Google\\Chrome",
    "name": "BackgroundModeEnabled",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.chrome-bookmarkbar": {
    "id": "br.policies.chrome-bookmarkbar",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Google\\Chrome",
    "name": "BookmarkBarEnabled",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.chrome-default-browser": {
    "id": "br.policies.chrome-default-browser",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Google\\Chrome",
    "name": "DefaultBrowserSettingEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.chrome-homepage": {
    "id": "br.policies.chrome-homepage",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Google\\Chrome",
    "name": "HomepageLocation",
    "on": "https://www.google.com",
    "off": null,
    "kind": "String",
    "admin": true
  },
  "br.policies.chrome-incognito": {
    "id": "br.policies.chrome-incognito",
    "op": "radio",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Google\\Chrome",
    "name": "IncognitoModeAvailability",
    "kind": "DWord",
    "options": [
      {
        "en": "Enabled",
        "zh": "啟用",
        "value": 0
      },
      {
        "en": "Disabled",
        "zh": "停用",
        "value": 1
      },
      {
        "en": "Forced",
        "zh": "強制",
        "value": 2
      }
    ],
    "admin": true
  },
  "br.policies.chrome-metrics": {
    "id": "br.policies.chrome-metrics",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Google\\Chrome",
    "name": "MetricsReportingEnabled",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.chrome-newtab": {
    "id": "br.policies.chrome-newtab",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Google\\Chrome",
    "name": "NewTabPageLocation",
    "on": "https://www.google.com",
    "off": null,
    "kind": "String",
    "admin": true
  },
  "br.policies.chrome-password-manager": {
    "id": "br.policies.chrome-password-manager",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Google\\Chrome",
    "name": "PasswordManagerEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.chrome-safebrowsing": {
    "id": "br.policies.chrome-safebrowsing",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Google\\Chrome",
    "name": "SafeBrowsingEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.edge-background-mode": {
    "id": "br.policies.edge-background-mode",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Edge",
    "name": "BackgroundModeEnabled",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.edge-default-browser": {
    "id": "br.policies.edge-default-browser",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Edge",
    "name": "DefaultBrowserSettingEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.edge-homepage": {
    "id": "br.policies.edge-homepage",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Edge",
    "name": "HomepageLocation",
    "on": "https://www.bing.com",
    "off": null,
    "kind": "String",
    "admin": true
  },
  "br.policies.edge-hubs-sidebar": {
    "id": "br.policies.edge-hubs-sidebar",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Edge",
    "name": "HubsSidebarEnabled",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.edge-inprivate": {
    "id": "br.policies.edge-inprivate",
    "op": "radio",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Edge",
    "name": "InPrivateModeAvailability",
    "kind": "DWord",
    "options": [
      {
        "en": "Enabled",
        "zh": "啟用",
        "value": 0
      },
      {
        "en": "Disabled",
        "zh": "停用",
        "value": 1
      },
      {
        "en": "Forced",
        "zh": "強制",
        "value": 2
      }
    ],
    "admin": true
  },
  "br.policies.edge-password-manager": {
    "id": "br.policies.edge-password-manager",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Edge",
    "name": "PasswordManagerEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.edge-personalization": {
    "id": "br.policies.edge-personalization",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Edge",
    "name": "PersonalizationReportingEnabled",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.edge-shopping": {
    "id": "br.policies.edge-shopping",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Edge",
    "name": "EdgeShoppingAssistantEnabled",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.edge-smartscreen": {
    "id": "br.policies.edge-smartscreen",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Edge",
    "name": "SmartScreenEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "br.policies.edge-startup-boost": {
    "id": "br.policies.edge-startup-boost",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Edge",
    "name": "StartupBoostEnabled",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "br.webtools.edge-efficiency-mode": {
    "id": "br.webtools.edge-efficiency-mode",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Policies\\Microsoft\\Edge",
    "name": "EfficiencyMode",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": false
  },
  "br.webtools.edge-startup-behavior": {
    "id": "br.webtools.edge-startup-behavior",
    "op": "radio",
    "root": "HKCU",
    "path": "Software\\Policies\\Microsoft\\Edge",
    "name": "RestoreOnStartup",
    "kind": "DWord",
    "options": [
      {
        "en": "Open new tab page",
        "zh": "開新分頁頁面",
        "value": 5
      },
      {
        "en": "Restore last session",
        "zh": "還原上次工作階段",
        "value": 1
      },
      {
        "en": "Open a set of pages",
        "zh": "開一組指定頁面",
        "value": 4
      }
    ],
    "admin": false
  },
  "explorer.checkboxes": {
    "id": "explorer.checkboxes",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "AutoCheckSelect",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "explorer.confirm-delete": {
    "id": "explorer.confirm-delete",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ConfirmFileDelete",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "explorer.full-path": {
    "id": "explorer.full-path",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CabinetState",
    "name": "FullPath",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "explorer.launch-to": {
    "id": "explorer.launch-to",
    "op": "radio",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "LaunchTo",
    "kind": "DWord",
    "options": [
      {
        "en": "This PC",
        "zh": "本機",
        "value": 1
      },
      {
        "en": "Home",
        "zh": "首頁",
        "value": 2
      }
    ],
    "admin": false
  },
  "explorer.nav-expand": {
    "id": "explorer.nav-expand",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "NavPaneExpandToCurrentFolder",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "explorer.separate-process": {
    "id": "explorer.separate-process",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "SeparateProcess",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "explorer.show-ext": {
    "id": "explorer.show-ext",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "HideFileExt",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "explorer.show-frequent": {
    "id": "explorer.show-frequent",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer",
    "name": "ShowFrequent",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "explorer.show-hidden": {
    "id": "explorer.show-hidden",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "Hidden",
    "on": 1,
    "off": 2,
    "kind": "DWord",
    "admin": false
  },
  "explorer.show-recent": {
    "id": "explorer.show-recent",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer",
    "name": "ShowRecent",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "explorer.show-super-hidden": {
    "id": "explorer.show-super-hidden",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ShowSuperHidden",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "performance.clear-pagefile": {
    "id": "performance.clear-pagefile",
    "op": "toggle",
    "root": "HKLM",
    "path": "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management",
    "name": "ClearPageFileAtShutdown",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "performance.fast-startup": {
    "id": "performance.fast-startup",
    "op": "toggle",
    "root": "HKLM",
    "path": "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Power",
    "name": "HiberbootEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "performance.game-dvr": {
    "id": "performance.game-dvr",
    "op": "toggle",
    "root": "HKCU",
    "path": "System\\GameConfigStore",
    "name": "GameDVR_Enabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "performance.game-mode": {
    "id": "performance.game-mode",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\GameBar",
    "name": "AutoGameModeEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "performance.power-throttling-off": {
    "id": "performance.power-throttling-off",
    "op": "toggle",
    "root": "HKLM",
    "path": "SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling",
    "name": "PowerThrottlingOff",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "performance.startup-delay-off": {
    "id": "performance.startup-delay-off",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Serialize",
    "name": "StartupDelayInMSec",
    "on": 0,
    "off": null,
    "kind": "DWord",
    "admin": false
  },
  "privacy.activity-history": {
    "id": "privacy.activity-history",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Windows\\System",
    "name": "PublishUserActivities",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "privacy.advertising-id": {
    "id": "privacy.advertising-id",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo",
    "name": "Enabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "privacy.app-launch-tracking": {
    "id": "privacy.app-launch-tracking",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "Start_TrackProgs",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "privacy.feedback-frequency": {
    "id": "privacy.feedback-frequency",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Siuf\\Rules",
    "name": "NumberOfSIUFInPeriod",
    "on": 0,
    "off": null,
    "kind": "DWord",
    "admin": false
  },
  "privacy.language-list-optout": {
    "id": "privacy.language-list-optout",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\International\\User Profile",
    "name": "HttpAcceptLanguageOptOut",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "privacy.location-access": {
    "id": "privacy.location-access",
    "op": "radio",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\location",
    "name": "Value",
    "kind": "String",
    "options": [
      {
        "en": "Allow",
        "zh": "允許",
        "value": "Allow"
      },
      {
        "en": "Deny",
        "zh": "拒絕",
        "value": "Deny"
      }
    ],
    "admin": false
  },
  "privacy.online-speech": {
    "id": "privacy.online-speech",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Speech_OneCore\\Settings\\OnlineSpeechPrivacy",
    "name": "HasAccepted",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "privacy.settings-suggestions": {
    "id": "privacy.settings-suggestions",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager",
    "name": "SubscribedContent-353694Enabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "privacy.softlanding-tips": {
    "id": "privacy.softlanding-tips",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager",
    "name": "SoftLandingEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "privacy.start-suggestions": {
    "id": "privacy.start-suggestions",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager",
    "name": "SubscribedContent-338388Enabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "privacy.tailored-experiences": {
    "id": "privacy.tailored-experiences",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Privacy",
    "name": "TailoredExperiencesWithDiagnosticDataEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "privacy.telemetry-level": {
    "id": "privacy.telemetry-level",
    "op": "radio",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection",
    "name": "AllowTelemetry",
    "kind": "DWord",
    "options": [
      {
        "en": "Security (Enterprise)",
        "zh": "安全（企業版）",
        "value": 0
      },
      {
        "en": "Required",
        "zh": "必要",
        "value": 1
      },
      {
        "en": "Optional",
        "zh": "選用",
        "value": 3
      }
    ],
    "admin": true
  },
  "privacy.usage-tips": {
    "id": "privacy.usage-tips",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager",
    "name": "SubscribedContent-338389Enabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "system.auto-reboot": {
    "id": "system.auto-reboot",
    "op": "toggle",
    "root": "HKLM",
    "path": "SYSTEM\\CurrentControlSet\\Control\\CrashControl",
    "name": "AutoReboot",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "system.clipboard-history": {
    "id": "system.clipboard-history",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Clipboard",
    "name": "EnableClipboardHistory",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "system.cloud-clipboard": {
    "id": "system.cloud-clipboard",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Clipboard",
    "name": "CloudClipboardAutomaticUpload",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "system.developer-mode": {
    "id": "system.developer-mode",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\AppModelUnlock",
    "name": "AllowDevelopmentWithoutDevLicense",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "system.linked-connections": {
    "id": "system.linked-connections",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System",
    "name": "EnableLinkedConnections",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "system.long-paths": {
    "id": "system.long-paths",
    "op": "toggle",
    "root": "HKLM",
    "path": "SYSTEM\\CurrentControlSet\\Control\\FileSystem",
    "name": "LongPathsEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "system.numlock-startup": {
    "id": "system.numlock-startup",
    "op": "radio",
    "root": "HKU",
    "path": ".DEFAULT\\Control Panel\\Keyboard",
    "name": "InitialKeyboardIndicators",
    "kind": "String",
    "options": [
      {
        "en": "On",
        "zh": "開",
        "value": "2"
      },
      {
        "en": "Off",
        "zh": "熄",
        "value": "0"
      }
    ],
    "admin": true
  },
  "system.verbose-status": {
    "id": "system.verbose-status",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System",
    "name": "VerboseStatus",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "taskbar.align": {
    "id": "taskbar.align",
    "op": "radio",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "TaskbarAl",
    "kind": "DWord",
    "options": [
      {
        "en": "Left",
        "zh": "靠左",
        "value": 0
      },
      {
        "en": "Center",
        "zh": "置中",
        "value": 1
      }
    ],
    "admin": false
  },
  "taskbar.chat": {
    "id": "taskbar.chat",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "TaskbarMn",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "taskbar.combine": {
    "id": "taskbar.combine",
    "op": "radio",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "TaskbarGlomLevel",
    "kind": "DWord",
    "options": [
      {
        "en": "Always combine",
        "zh": "永遠合併",
        "value": 0
      },
      {
        "en": "When taskbar is full",
        "zh": "工作列滿先合併",
        "value": 1
      },
      {
        "en": "Never",
        "zh": "永不合併",
        "value": 2
      }
    ],
    "admin": false
  },
  "taskbar.end-task": {
    "id": "taskbar.end-task",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\TaskbarDeveloperSettings",
    "name": "TaskbarEndTask",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "taskbar.multi-monitor-all": {
    "id": "taskbar.multi-monitor-all",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "MMTaskbarEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "taskbar.search-mode": {
    "id": "taskbar.search-mode",
    "op": "radio",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Search",
    "name": "SearchboxTaskbarMode",
    "kind": "DWord",
    "options": [
      {
        "en": "Hidden",
        "zh": "隱藏",
        "value": 0
      },
      {
        "en": "Icon only",
        "zh": "只顯示圖示",
        "value": 1
      },
      {
        "en": "Search box",
        "zh": "搜尋框",
        "value": 2
      },
      {
        "en": "Icon and label",
        "zh": "圖示同標籤",
        "value": 3
      }
    ],
    "admin": false
  },
  "taskbar.show-all-tray-icons": {
    "id": "taskbar.show-all-tray-icons",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer",
    "name": "EnableAutoTray",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "taskbar.show-seconds-clock": {
    "id": "taskbar.show-seconds-clock",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ShowSecondsInSystemClock",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "taskbar.start-most-used": {
    "id": "taskbar.start-most-used",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "Start_TrackProgs",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "taskbar.start-recently-added": {
    "id": "taskbar.start-recently-added",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "Start_TrackDocs",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "taskbar.start-recommendations": {
    "id": "taskbar.start-recommendations",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "Start_IrisRecommendations",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "taskbar.task-view": {
    "id": "taskbar.task-view",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ShowTaskViewButton",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "taskbar.widgets": {
    "id": "taskbar.widgets",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "TaskbarDa",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.classic-volume-mixer": {
    "id": "w11p.explorermore.classic-volume-mixer",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\MTCUVC",
    "name": "EnableMtcUvc",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "w11p.explorermore.clock-seconds": {
    "id": "w11p.explorermore.clock-seconds",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ShowSecondsInSystemClock",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.confirm-file-delete": {
    "id": "w11p.explorermore.confirm-file-delete",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ConfirmFileDelete",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.disable-bing-search": {
    "id": "w11p.explorermore.disable-bing-search",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Search",
    "name": "BingSearchEnabled",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.disable-lockscreen": {
    "id": "w11p.explorermore.disable-lockscreen",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Windows\\Personalization",
    "name": "NoLockScreen",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "w11p.explorermore.disable-shake": {
    "id": "w11p.explorermore.disable-shake",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "DisallowShaking",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.disable-start-websearch": {
    "id": "w11p.explorermore.disable-start-websearch",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Policies\\Microsoft\\Windows\\Explorer",
    "name": "DisableSearchBoxSuggestions",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.disable-thumb-cache": {
    "id": "w11p.explorermore.disable-thumb-cache",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "DisableThumbnailCache",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.expand-ribbon": {
    "id": "w11p.explorermore.expand-ribbon",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Ribbon",
    "name": "MinimizedStateTabletModeOff",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.file-op-details": {
    "id": "w11p.explorermore.file-op-details",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\OperationStatusManager",
    "name": "EnthusiastMode",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.max-icon-cache": {
    "id": "w11p.explorermore.max-icon-cache",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer",
    "name": "Max Cached Icons",
    "on": "4096",
    "off": "2000",
    "kind": "String",
    "admin": true
  },
  "w11p.explorermore.no-frequent-quickaccess": {
    "id": "w11p.explorermore.no-frequent-quickaccess",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer",
    "name": "ShowFrequent",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.no-recent-quickaccess": {
    "id": "w11p.explorermore.no-recent-quickaccess",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer",
    "name": "ShowRecent",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.remove-3d-objects": {
    "id": "w11p.explorermore.remove-3d-objects",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\MyComputer\\NameSpace\\{0DB7E03F-FC29-4DC6-9020-FF41B59E513A}",
    "name": "ThisPCPolicy",
    "on": "Hide",
    "off": "Show",
    "kind": "String",
    "admin": true
  },
  "w11p.explorermore.restore-folders": {
    "id": "w11p.explorermore.restore-folders",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "PersistBrowsers",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.separate-process": {
    "id": "w11p.explorermore.separate-process",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "SeparateProcess",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.explorermore.tray-all-icons": {
    "id": "w11p.explorermore.tray-all-icons",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer",
    "name": "EnableAutoTray",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "w11p.inputintl.filter-keys": {
    "id": "w11p.inputintl.filter-keys",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Accessibility\\Keyboard Response",
    "name": "Flags",
    "on": "27",
    "off": "126",
    "kind": "String",
    "admin": false
  },
  "w11p.inputintl.mouse-accel": {
    "id": "w11p.inputintl.mouse-accel",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Mouse",
    "name": "MouseSpeed",
    "on": "0",
    "off": "1",
    "kind": "String",
    "admin": false
  },
  "w11p.inputintl.mouse-threshold1": {
    "id": "w11p.inputintl.mouse-threshold1",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Mouse",
    "name": "MouseThreshold1",
    "on": "0",
    "off": "6",
    "kind": "String",
    "admin": false
  },
  "w11p.inputintl.mouse-threshold2": {
    "id": "w11p.inputintl.mouse-threshold2",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Mouse",
    "name": "MouseThreshold2",
    "on": "0",
    "off": "10",
    "kind": "String",
    "admin": false
  },
  "w11p.inputintl.sticky-keys": {
    "id": "w11p.inputintl.sticky-keys",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Accessibility\\StickyKeys",
    "name": "Flags",
    "on": "511",
    "off": "510",
    "kind": "String",
    "admin": false
  },
  "w11p.inputintl.swap-mouse-buttons": {
    "id": "w11p.inputintl.swap-mouse-buttons",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Mouse",
    "name": "SwapMouseButtons",
    "on": "1",
    "off": "0",
    "kind": "String",
    "admin": false
  },
  "w11p.inputintl.toggle-keys": {
    "id": "w11p.inputintl.toggle-keys",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Accessibility\\ToggleKeys",
    "name": "Flags",
    "on": "63",
    "off": "62",
    "kind": "String",
    "admin": false
  },
  "w11p.perfboot.hags": {
    "id": "w11p.perfboot.hags",
    "op": "toggle",
    "root": "HKLM",
    "path": "SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers",
    "name": "HwSchMode",
    "on": 2,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "w11p.perfboot.rebuild-search-index": {
    "id": "w11p.perfboot.rebuild-search-index",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows Search",
    "name": "SetupCompletedSuccessfully",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "w11p.perfboot.startup-delay": {
    "id": "w11p.perfboot.startup-delay",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Serialize",
    "name": "StartupDelayInMSec",
    "on": 0,
    "off": null,
    "kind": "DWord",
    "admin": false
  },
  "w11p.perfboot.tdr-delay": {
    "id": "w11p.perfboot.tdr-delay",
    "op": "toggle",
    "root": "HKLM",
    "path": "SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers",
    "name": "TdrDelay",
    "on": 8,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "w11p.storagenotif.joint-resize": {
    "id": "w11p.storagenotif.joint-resize",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "JointResize",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.lockscreen-notifications": {
    "id": "w11p.storagenotif.lockscreen-notifications",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Notifications\\Settings",
    "name": "NOC_GLOBAL_SETTING_ALLOW_TOASTS_ABOVE_LOCK",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.notification-sound": {
    "id": "w11p.storagenotif.notification-sound",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Notifications\\Settings",
    "name": "NOC_GLOBAL_SETTING_ALLOW_NOTIFICATION_SOUND",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.notifications-global": {
    "id": "w11p.storagenotif.notifications-global",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Notifications\\Settings",
    "name": "NOC_GLOBAL_SETTING_TOASTS_ENABLED",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.show-snap-tips": {
    "id": "w11p.storagenotif.show-snap-tips",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "EnableSnapAssistFlyout2",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.snap-assist": {
    "id": "w11p.storagenotif.snap-assist",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "SnapAssist",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.snap-bar": {
    "id": "w11p.storagenotif.snap-bar",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "EnableSnapBar",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.snap-fill": {
    "id": "w11p.storagenotif.snap-fill",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "SnapFill",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.snap-flyout": {
    "id": "w11p.storagenotif.snap-flyout",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "EnableSnapAssistFlyout",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.snap-suggestions": {
    "id": "w11p.storagenotif.snap-suggestions",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "SnapAssistSuggestions",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.vd-all-monitors": {
    "id": "w11p.storagenotif.vd-all-monitors",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "VirtualDesktopAllMonitorsEnabled",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "w11p.storagenotif.window-arrangement": {
    "id": "w11p.storagenotif.window-arrangement",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Desktop",
    "name": "WindowArrangementActive",
    "on": "1",
    "off": "0",
    "kind": "String",
    "admin": false
  },
  "winaero.appearance.accent-start-taskbar": {
    "id": "winaero.appearance.accent-start-taskbar",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",
    "name": "ColorPrevalence",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "winaero.appearance.colored-title-bars": {
    "id": "winaero.appearance.colored-title-bars",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\DWM",
    "name": "ColorPrevalence",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "winaero.appearance.disable-aero-shake": {
    "id": "winaero.appearance.disable-aero-shake",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "DisallowShaking",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "winaero.appearance.inactive-title-bar-color": {
    "id": "winaero.appearance.inactive-title-bar-color",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\DWM",
    "name": "AccentColorInactive",
    "on": 8421504,
    "off": null,
    "kind": "DWord",
    "admin": false
  },
  "winaero.appearance.legacy-balloon-notifications": {
    "id": "winaero.appearance.legacy-balloon-notifications",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Policies\\Microsoft\\Windows\\Explorer",
    "name": "EnableLegacyBalloonNotifications",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": false
  },
  "winaero.behavior.auto-end-tasks": {
    "id": "winaero.behavior.auto-end-tasks",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Desktop",
    "name": "AutoEndTasks",
    "on": "1",
    "off": "0",
    "kind": "String",
    "admin": false
  },
  "winaero.behavior.disable-win-l-lock": {
    "id": "winaero.behavior.disable-win-l-lock",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System",
    "name": "DisableLockWorkstation",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": false
  },
  "winaero.behavior.hung-app-timeout": {
    "id": "winaero.behavior.hung-app-timeout",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Desktop",
    "name": "HungAppTimeout",
    "on": "1000",
    "off": null,
    "kind": "String",
    "admin": false
  },
  "winaero.behavior.shutdown-event-tracker": {
    "id": "winaero.behavior.shutdown-event-tracker",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Reliability",
    "name": "ShutdownReasonUI",
    "on": 0,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "winaero.behavior.wait-to-kill-app-timeout": {
    "id": "winaero.behavior.wait-to-kill-app-timeout",
    "op": "toggle",
    "root": "HKCU",
    "path": "Control Panel\\Desktop",
    "name": "WaitToKillAppTimeout",
    "on": "2000",
    "off": null,
    "kind": "String",
    "admin": false
  },
  "winaero.boot-logon.disable-acrylic-blur-logon": {
    "id": "winaero.boot-logon.disable-acrylic-blur-logon",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Windows\\System",
    "name": "DisableAcrylicBackgroundOnLogon",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "winaero.boot-logon.disable-auto-restart-signon": {
    "id": "winaero.boot-logon.disable-auto-restart-signon",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System",
    "name": "DisableAutomaticRestartSignOn",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "winaero.boot-logon.disable-cad": {
    "id": "winaero.boot-logon.disable-cad",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System",
    "name": "DisableCAD",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "winaero.boot-logon.disable-logon-background-image": {
    "id": "winaero.boot-logon.disable-logon-background-image",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Windows\\System",
    "name": "DisableLogonBackgroundImage",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "winaero.boot-logon.disable-startup-sound": {
    "id": "winaero.boot-logon.disable-startup-sound",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Authentication\\LogonUI\\BootAnimation",
    "name": "DisableStartupSound",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "winaero.boot-logon.display-last-logon-info": {
    "id": "winaero.boot-logon.display-last-logon-info",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System",
    "name": "DisplayLastLogonInfo",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "winaero.boot-logon.no-lock-screen": {
    "id": "winaero.boot-logon.no-lock-screen",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Windows\\Personalization",
    "name": "NoLockScreen",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "winaero.boot-logon.numlock-at-startup": {
    "id": "winaero.boot-logon.numlock-at-startup",
    "op": "toggle",
    "root": "HKU",
    "path": ".DEFAULT\\Control Panel\\Keyboard",
    "name": "InitialKeyboardIndicators",
    "on": "2147483650",
    "off": "2147483648",
    "kind": "String",
    "admin": true
  },
  "winaero.context-menu.remove-cast-to-device": {
    "id": "winaero.context-menu.remove-cast-to-device",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Shell Extensions\\Blocked",
    "name": "{7AD84985-87B4-4a16-BE58-8B72A5B390F7}",
    "on": "",
    "off": null,
    "kind": "String",
    "admin": false
  },
  "winaero.context-menu.remove-edit-with-photos": {
    "id": "winaero.context-menu.remove-edit-with-photos",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Shell Extensions\\Blocked",
    "name": "{BFE0E2A4-C70C-4AD7-AC3D-10D1ECEBB5B4}",
    "on": "",
    "off": null,
    "kind": "String",
    "admin": false
  },
  "winaero.context-menu.remove-give-access-share": {
    "id": "winaero.context-menu.remove-give-access-share",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Shell Extensions\\Blocked",
    "name": "{f81e9010-6ea4-11ce-a7ff-00aa003ca9f6}",
    "on": "",
    "off": null,
    "kind": "String",
    "admin": false
  },
  "winaero.context-menu.remove-restore-previous-versions": {
    "id": "winaero.context-menu.remove-restore-previous-versions",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Shell Extensions\\Blocked",
    "name": "{596AB062-B4D2-4215-9F74-E9109B0A8153}",
    "on": "",
    "off": null,
    "kind": "String",
    "admin": false
  },
  "winaero.context-menu.remove-scan-with-defender": {
    "id": "winaero.context-menu.remove-scan-with-defender",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Shell Extensions\\Blocked",
    "name": "{09A47860-11B0-4DA5-AFA5-26D86198A780}",
    "on": "",
    "off": null,
    "kind": "String",
    "admin": false
  },
  "winaero.desktop-explorer.checkboxes-select": {
    "id": "winaero.desktop-explorer.checkboxes-select",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "AutoCheckSelect",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "winaero.desktop-explorer.compact-mode": {
    "id": "winaero.desktop-explorer.compact-mode",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "UseCompactMode",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "winaero.desktop-explorer.disable-thumbnail-cache": {
    "id": "winaero.desktop-explorer.disable-thumbnail-cache",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "DisableThumbnailCache",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "winaero.desktop-explorer.drive-letters-first": {
    "id": "winaero.desktop-explorer.drive-letters-first",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer",
    "name": "ShowDriveLettersFirst",
    "on": 4,
    "off": 0,
    "kind": "DWord",
    "admin": true
  },
  "winaero.desktop-explorer.expand-to-current-folder": {
    "id": "winaero.desktop-explorer.expand-to-current-folder",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "NavPaneExpandToCurrentFolder",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "winaero.desktop-explorer.launch-to-this-pc": {
    "id": "winaero.desktop-explorer.launch-to-this-pc",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "LaunchTo",
    "on": 1,
    "off": 2,
    "kind": "DWord",
    "admin": false
  },
  "winaero.desktop-explorer.no-recent-files-explorer": {
    "id": "winaero.desktop-explorer.no-recent-files-explorer",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer",
    "name": "ShowRecent",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "winaero.desktop-explorer.show-seconds-clock": {
    "id": "winaero.desktop-explorer.show-seconds-clock",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ShowSecondsInSystemClock",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "winaero.desktop-explorer.show-status-bar": {
    "id": "winaero.desktop-explorer.show-status-bar",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "ShowStatusBar",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "winaero.desktop-explorer.taskbar-end-task": {
    "id": "winaero.desktop-explorer.taskbar-end-task",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\TaskbarDeveloperSettings",
    "name": "TaskbarEndTask",
    "on": 1,
    "off": 0,
    "kind": "DWord",
    "admin": false
  },
  "winaero.privacy-network.delivery-optimization-no-peering": {
    "id": "winaero.privacy-network.delivery-optimization-no-peering",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Windows\\DeliveryOptimization",
    "name": "DODownloadMode",
    "on": 0,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "winaero.privacy-network.deny-apps-location": {
    "id": "winaero.privacy-network.deny-apps-location",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy",
    "name": "LetAppsAccessLocation",
    "on": 2,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "winaero.privacy-network.disable-app-launch-tracking": {
    "id": "winaero.privacy-network.disable-app-launch-tracking",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
    "name": "Start_TrackProgs",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "winaero.privacy-network.disable-feedback-frequency": {
    "id": "winaero.privacy-network.disable-feedback-frequency",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Siuf\\Rules",
    "name": "NumberOfSIUFInPeriod",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "winaero.privacy-network.disable-feedback-notifications": {
    "id": "winaero.privacy-network.disable-feedback-notifications",
    "op": "toggle",
    "root": "HKLM",
    "path": "SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection",
    "name": "DoNotShowFeedbackNotifications",
    "on": 1,
    "off": null,
    "kind": "DWord",
    "admin": true
  },
  "winaero.privacy-network.disable-tailored-experiences": {
    "id": "winaero.privacy-network.disable-tailored-experiences",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Windows\\CurrentVersion\\Privacy",
    "name": "TailoredExperiencesWithDiagnosticDataEnabled",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  },
  "winaero.privacy-network.disable-telemetry-autologger": {
    "id": "winaero.privacy-network.disable-telemetry-autologger",
    "op": "toggle",
    "root": "HKLM",
    "path": "SYSTEM\\CurrentControlSet\\Control\\WMI\\AutoLogger\\AutoLogger-Diagtrack-Listener",
    "name": "Start",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": true
  },
  "winaero.privacy-network.disable-typing-insights": {
    "id": "winaero.privacy-network.disable-typing-insights",
    "op": "toggle",
    "root": "HKCU",
    "path": "Software\\Microsoft\\Input\\Settings",
    "name": "InsightsEnabled",
    "on": 0,
    "off": 1,
    "kind": "DWord",
    "admin": false
  }
};

export const tweakOpCount = 166;

/** The registry op for a tweak id, or undefined if it isn't one of the applyable uniform tweaks. */
export function opFor(id: string): TweakOp | undefined {
  return tweakOps[id];
}
